# Generated by Django 5.2.4 on 2025-07-31 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='tache',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tache',
            name='est_terminee',
            field=models.BooleanField(default=False),
        ),
    ]
