# Generated by Django 5.2.4 on 2025-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0002_remove_tache_date_creation_tache_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
